### ISSUE TITLE
Failed to load the linter-julia package

### ISSUE THREAD

**Issue by mansterx** [AtomLinter/linter-julia#45]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Linux Mint
**Thrown From**: [linter-julia](https://github.com/TeroFrondelius/linter-julia) package 0.7.2

### Stack Trace

Failed to load the linter-julia package

```
At Cannot find module 'tmp'

Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-julia/lib/linter-julia.coffee:3:7)
    at /packages/linter-julia/lib/linter-julia.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:887:35)
    at /usr/share/atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:565:22)
    at /usr/share/atom/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:473:25)
    at /usr/share/atom/resources/app/src/atom-environment.js:812:34
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.2 
atom-python-run 0.7.3 
autocomplete-python 1.8.64 
build 0.68.0 
build-python 0.9.2 
busy 0.7.0 
busy-signal 1.4.3 
format-standard 4.3.0 
formatter-jsbeautify 1.0.2 
ink 0.7.4 
intentions 1.1.2 
julia-client 0.6.0 
julia-ide 0.3.0 
language-julia 0.6.0 
latex-completions 0.3.2 
linter 2.2.0 
linter-julia 0.7.2 
linter-ui-default 1.2.4 
python-debugger 0.2.0 
python-tools 0.6.9 
react-es6-snippets 0.3.0 
standard-formatter 2.8.0 
Sublime-Style-Column-Selection 1.7.4 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by Arcanemagus** [comment]
Try re-installing the package, occasionally APM fails to install all required dependencies.
