### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Dlng** [AtomLinter/linter-julia#46]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter-julia](https://github.com/TeroFrondelius/linter-julia) package 0.7.2

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Users/Weilong/Desktop/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /packages/linter-julia/lib/linter-julia.coffee:93:26)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  2x -2:36.4.0 editor:newline (input.hidden-input)
  2x -2:32.6.0 core:save (input.hidden-input)
     -2:23.2.0 julia-client:run-file (ul.list-inline.tab-bar.inset-panel)
     -1:49.7.0 core:select-right (input.hidden-input)
     -1:49 core:backspace (input.hidden-input)
 10x -1:47.1.0 core:move-down (input.hidden-input)
     -1:20.9.0 core:save (input.hidden-input)
     -1:07.4.0 core:move-left (input.hidden-input)
     -0:57.6.0 core:backspace (input.hidden-input)
  2x -0:56.1.0 core:move-up (input.hidden-input)
     -0:55.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:55.3.0 snippets:expand (input.hidden-input)
     -0:55.3.0 editor:indent (input.hidden-input)
     -0:53.7.0 core:move-down (input.hidden-input)
     -0:53.3.0 core:move-up (input.hidden-input)
 13x -0:49.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
indent-detective 0.1.1 
ink 0.7.7 
intentions 1.1.5 
julia-client 0.6.4 
language-julia 0.12.0 
latex-completions 0.3.3 
linter 2.2.0 
linter-julia 0.7.2 
linter-ui-default 1.6.10 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by MMalakhov** [comment]
So, How should I fix it? There is long board at #38 and I can't found anything for solution  in it

**Comment by TeroFrondelius** [comment]
Use the master version. The new fixed version haven't been raged.

**Comment by Arcanemagus** [comment]
Closing based on the above comment.
