### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by GantZA** [AtomLinter/linter-julia#58]
On opening a julia script in Atom, an Error message pops up saying:
 [Linter] Error running Julia
See Console for more info

I have pointed the linter-julia package to the bin/julia file so I don't think that is the issue.

Opening the console shows this error
```

(anonymous) @ /home/gant/.atom/packages/linter/lib/linter-registry.js:155
/home/gant/.atom/packages/linter/lib/linter-registry.js:155 [Linter] Error running Julia TypeError: _uuid42.default.sync is not a function
    at /home/gant/.atom/packages/linter-julia/lib/server.js:15:25
    at Generator.next (<anonymous>)
    at step (/home/gant/.atom/packages/linter-julia/lib/server.js:61:2)
    at /home/gant/.atom/packages/linter-julia/lib/server.js:61:2
    at Promise (<anonymous>)
    at /home/gant/.atom/packages/linter-julia/lib/server.js:61:2
    at /home/gant/.atom/packages/linter-julia/lib/server.js:20:22
    at Generator.next (<anonymous>)
    at step (/home/gant/.atom/packages/linter-julia/lib/server.js:61:2)
    at /home/gant/.atom/packages/linter-julia/lib/server.js:61:2
    at Promise (<anonymous>)
    at /home/gant/.atom/packages/linter-julia/lib/server.js:61:2
    at Object.<anonymous> (/home/gant/.atom/packages/linter-julia/lib/index.js:63:31)
    at Generator.next (<anonymous>)
    at step (/home/gant/.atom/packages/linter-julia/lib/index.js:10:273)
    at /home/gant/.atom/packages/linter-julia/lib/index.js:10:443
    at Promise (<anonymous>)
    at Object.lint (/home/gant/.atom/packages/linter-julia/lib/index.js:10:99)
    at promises.push.Promise.then._this2.emitter.emit.number (/home/gant/.atom/packages/linter/lib/linter-registry.js:113:26)
    at Promise (<anonymous>)
    at _loop (/home/gant/.atom/packages/linter/lib/linter-registry.js:111:9)
    at LinterRegistry.<anonymous> (/home/gant/.atom/packages/linter/lib/linter-registry.js:98:40)
    at Generator.next (<anonymous>)
    at LinterRegistry.<anonymous> (/home/gant/.atom/packages/linter/lib/linter-registry.js:178:4)
    at Generator.next (<anonymous>)
    at step (/home/gant/.atom/packages/linter/lib/linter-registry.js:9:273)
    at /home/gant/.atom/packages/linter/lib/linter-registry.js:9:443
    at Promise (<anonymous>)
    at LinterRegistry.<anonymous> (/home/gant/.atom/packages/linter/lib/linter-registry.js:9:99)
    at /home/gant/.atom/packages/linter/lib/main.js:114:30
(anonymous) @ /home/gant/.atom/packages/linter/lib/linter-registry.js:155
```

**Comment by Arcanemagus** [comment]
Confirmed bug, I'm not sure why the code was written that way since that has _never_ been valid syntax.

It looks like `Lint.jl` itself isn't able to run on anything newer than Julia 0.5.2 at the moment though.
