### ISSUE TITLE
Cannot find module 'uuid4'

### ISSUE THREAD

**Issue by aminya** [AtomLinter/linter-julia#75]
Using my branch: https://github.com/AtomLinter/linter-julia/pull/74
```
Error: Cannot find module 'uuid4'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/AminDATA/Julia/linter-julia/lib/server.js:5:24)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/AminDATA/Julia/linter-julia/lib/server.js:71:2)
    at Module.get_Module._compile (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/AminDATA/Julia/linter-julia/lib/index.js:4:43)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/AminDATA/Julia/linter-julia/lib/index.js:115:2)
    at Module.get_Module._compile (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:1:727373)
    at Package.requireMainModule (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3325206)
    at Package.activateNow (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3313190)
    at measure (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312968)
    at Package.measure (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3310578)
    at activationPromise.activationPromise.Promise (C:\Users\yahyaaba\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312828)
    at new Promise (<anonymous>)
```

**Comment by aminya** [comment]
It is because the package need deployement for using
